@startuml

hide footbox

participant ":EditCardCommand" as EditCardCommand
participant ":Deck" as Deck
participant ":FlashCard" as FlashCard
participant ":CardLiUI" as CardLiUI
actor "User" as User

[-> EditCardCommand : new
activate EditCardCommand
[<-- EditCardCommand : command
deactivate EditCardCommand

[->EditCardCommand : execute()
activate EditCardCommand

EditCardCommand -> EditCardCommand : prepareEditCardCommand()
activate EditCardCommand

EditCardCommand -> EditCardCommand: prepareCardIndex(card, deck)
activate EditCardCommand

EditCardCommand --> EditCardCommand: card
deactivate EditCardCommand

EditCardCommand --> EditCardCommand: preparedArguments
deactivate EditCardCommand

EditCardCommand -> Deck: editCard(parameters)
activate Deck


alt front
    Deck -> FlashCard: setFront(changeTo)
    activate FlashCard
    deactivate FlashCard
else back
    Deck -> FlashCard: setBack(changeTo)
    activate FlashCard
    deactivate FlashCard
end

destroy FlashCard

Deck --> EditCardCommand: message
deactivate Deck

destroy Deck

[<-- EditCardCommand: result
deactivate EditCardCommand
destroy EditCardCommand

[-> CardLiUI: printResult(result)
activate CardLiUI

CardLiUI -> User

deactivate CardLiUI
destroy CardLiUI
@enduml