@startuml

hide footbox

participant ":EditDeckCommand" as EditDeckCommand
participant ":DeckManager" as DeckManager
participant ":Deck" as Deck
participant ":CardLiUI" as CardLiUI
actor "User" as User

[-> EditDeckCommand : new
activate EditDeckCommand
[<-- EditDeckCommand : command
deactivate EditDeckCommand

[->EditDeckCommand : execute()
activate EditDeckCommand

EditDeckCommand -> EditDeckCommand : prepareEditDeckCommand()
activate EditDeckCommand

EditDeckCommand -> EditDeckCommand: prepareDeckIndex(deck, deckManager)
activate EditDeckCommand

EditDeckCommand --> EditDeckCommand: deck
deactivate EditDeckCommand

EditDeckCommand --> EditDeckCommand: preparedArguments
deactivate EditDeckCommand

EditDeckCommand -> DeckManager: editDeck(parameters)
activate DeckManager

DeckManager -> Deck: setName(deckName)
activate Deck
deactivate Deck

destroy Deck

DeckManager --> EditDeckCommand: message
deactivate DeckManager

destroy DeckManager

[<-- EditDeckCommand: result
deactivate EditDeckCommand
destroy EditDeckCommand

[-> CardLiUI: printResult(result)
activate CardLiUI

CardLiUI -> User

deactivate CardLiUI
destroy CardLiUI

@enduml