@startuml
!include style.puml

hide footbox
autonumber

participant ":CardLI" as CardLI mainCOLOUR
participant "innerParser:InnerParser" as InnerParser logicCOLOUR
participant "command:EditCardCommand" as EditCardCommand logicCOLOUR
participant ":Deck" as Deck modelCOLOUR
participant ":FlashCard" as FlashCard modelCOLOUR
participant "ui:CardLiUI" as CardLiUI uiCOLOUR
actor "User" as User

CardLI -> InnerParser: parseCommand(input)
activate InnerParser

ref over InnerParser
getCommandArguments(commandType,input)
end ref

InnerParser -> EditCardCommand** : new EditCardCommand(arguments)
activate EditCardCommand
InnerParser <-- EditCardCommand : command
deactivate EditCardCommand
InnerParser --> CardLI: command
deactivate InnerParser

CardLI -> EditCardCommand : execute()
activate EditCardCommand

ref over EditCardCommand
    prepareEditCardCommand()
end ref

EditCardCommand -> Deck: editCard(parameters)
activate Deck

alt front
    Deck -> FlashCard: setFront(changeTo)
    activate FlashCard
    deactivate FlashCard
else back
    Deck -> FlashCard: setBack(changeTo)
    activate FlashCard
    deactivate FlashCard
end


Deck --> EditCardCommand: message
deactivate Deck

CardLI<-- EditCardCommand: result
deactivate EditCardCommand
destroy EditCardCommand

CardLI -> CardLiUI: printResult(result)
activate CardLiUI

CardLiUI -> User

deactivate CardLiUI
@enduml