@startuml
!include style.puml
autonumber
hide footbox

participant ":TestManager" as TestManager modelCOLOUR
participant ":AnswerList" as AnswerList modelCOLOUR
participant ":DeckManager" as DeckManager modelCOLOUR
participant "deckToTest:Deck" as Deck modelCOLOUR

activate TestManager

TestManager -> DeckManager : getTestDeck(deckIndex:int)
activate DeckManager

alt test all decks
DeckManager -> Deck **: Deck()
activate Deck
loop every Deck in DeckManager
loop every FlashCard in Deck

Deck -> Deck : addFlashCard()
activate Deck
Deck --> Deck
deactivate Deck

end
end
Deck --> DeckManager
deactivate Deck
DeckManager --> TestManager : deckToTest

else test single deck
TestManager -> DeckManager : get(deckIndex)
DeckManager --> TestManager : deckToTest
end
deactivate DeckManager
destroy DeckManager

TestManager -> AnswerList **: AnswerList(deckToTest)
activate AnswerList

TestManager <-- AnswerList : userAnswers
deactivate AnswerList

@enduml