@startuml
participant ":TestManager" as TestManager
participant ":AnswerList" as AnswerList
participant ":DeckManager" as DeckManager
participant "deckToTest:Deck" as Deck

activate TestManager

TestManager -> DeckManager : getTestDeck(deckIndex:int)
activate DeckManager

alt test all decks
DeckManager -> Deck **: Deck()
activate Deck
loop every Deck in DeckManager
loop every FlashCard in Deck

Deck -> Deck : addFlashCard()
activate Deck
Deck --> Deck
deactivate Deck

end
end
Deck --> DeckManager
deactivate Deck
DeckManager --> TestManager : deckToTest

else test single deck
TestManager -> DeckManager : get(deckIndex)
DeckManager --> TestManager : deckToTest
end
deactivate DeckManager

TestManager -> AnswerList **: AnswerList(deckToTest)
activate AnswerList

TestManager <-- AnswerList : userAnswers
deactivate AnswerList

@enduml