@startuml
!include style.puml

hide footbox
autonumber

participant ":CardLI" as CardLI mainCOLOUR
participant "innerParser:InnerParser" as InnerParser logicCOLOUR
participant "command:MoveCardCommand" as MoveCardCommand logicCOLOUR
participant ":DeckManager" as DeckManager modelCOLOUR
participant ":Deck" as Deck modelCOLOUR
participant "ui:CardLiUI" as CardLiUI uiCOLOUR
actor "User" as User

CardLI -> InnerParser: parseCommand(input)
activate InnerParser

InnerParser -> MoveCardCommand**: new MoveCardCommand(arguments)
activate MoveCardCommand
MoveCardCommand --> InnerParser: "command:MoveCardCommand
deactivate MoveCardCommand
InnerParser --> CardLI: command
deactivate InnerParser

CardLI->MoveCardCommand : execute()
activate MoveCardCommand

ref over MoveCardCommand
prepareMoveCardCommand()
end ref

MoveCardCommand -> DeckManager: moveCard(parameters)
activate DeckManager

DeckManager -> Deck: getCard(cardIndex)
activate Deck

Deck --> DeckManager: cardCopy
deactivate Deck

DeckManager -> Deck: addFlashCard(cardCopy)
activate Deck
deactivate Deck

DeckManager -> Deck: deleteFlashCard(enteredCardIndex)
activate Deck
deactivate Deck
destroy Deck

DeckManager --> MoveCardCommand: message
deactivate DeckManager

destroy DeckManager

CardLI<-- MoveCardCommand: result
deactivate MoveCardCommand
destroy MoveCardCommand

CardLI-> CardLiUI: printResult(result)
activate CardLiUI

CardLiUI -> User

deactivate CardLiUI
@enduml