@startuml
!include style.puml
autonumber
hide footbox

participant ":TestManager" as TestManager modelCOLOUR
participant ":AnswerList" as AnswerList modelCOLOUR
participant ":Collections" as Collections
participant "ShuffledDeck:Deck" as Deck modelCOLOUR

activate TestManager

TestManager -> TestManager : prepareTestDeck(userAnswers)
activate TestManager

TestManager -> Collections : shuffle(deckToTest)
activate Collections

Collections --> TestManager : ShuffledDeck
deactivate Collections

loop every card in deckToTest
TestManager -> AnswerList : getDeck()
activate AnswerList
AnswerList -> Deck : getQuestionNumber(question:FlashCard)
activate Deck
Deck --> AnswerList : questionNumber:Int
deactivate Deck
AnswerList --> TestManager : questionNumber:Int
deactivate AnswerList

TestManager -> AnswerList : addAnswer("NIL", questionNumber)
activate AnswerList
AnswerList --> TestManager
deactivate AnswerList
end

TestManager --> TestManager
deactivate TestManager
@enduml
