@startuml
!include style.puml
autonumber
hide footbox

participant ":TestManager" as TestManager modelCOLOUR
participant "countdown:Countdown" as Countdown modelCOLOUR
activate TestManager


TestManager -> TestManager : testInProgress(shuffledDeckToTest, userAnswers)
activate TestManager

TestManager -> Countdown **: Countdown(timer:Int, TIMES_UP_MESSAGE:String)
activate Countdown

Countdown --> TestManager
deactivate Countdown

loop until every card in deckToTest is answered && countdown.isRunning()
loop currentQuestion >= 0 && currentQuestion < deckReplicate.size() && countdown.isRunning()
opt current question is not answered
TestManager -> TestManager : testCard(userAnswer, currentQuestion:FlashCard, countdown)
activate TestManager
TestManager --> TestManager : nextQuestionFlag:Int
deactivate TestManager
end
end
end
opt countdown.isRunning
TestManager -> Countdown : stop()
activate Countdown
deactivate Countdown
end
TestManager --> TestManager
deactivate TestManager
destroy Countdown

@enduml